### ISSUE TITLE
[BUG] <title>

### ISSUE THREAD

**Issue by greedyro** [linuxserver/docker-heimdall#133]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Instead of heimdall apearing in the broser i get: "504 Gateway Time-out
nginx", and in docker logs i get a PHP fatal error

### Steps To Reproduce

1. start the docker
2. after it says in docker logs that it's done
3. when navigating to the address (for http for example with :80)
4. in logs appears a PHP error
5. and in the browser it says: "504 Gateway Time-out
nginx"

### Environment

```markdown
- OS: debian
- How docker service was installed:
with docker compose from portainer using :
---
version: "2.1"
services:
  heimdall:
    image: lscr.io/linuxserver/heimdall
    container_name: heimdall
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Bucharest
    volumes:
      - /mnt/prox-share/docker/config/heimdall:/config
    ports:
      - 83:80
      - 443:443
    restart: unless-stopped
```

### CPU architecture

x86-64

### Docker creation

```bash
---
version: "2.1"
services:
  heimdall:
    image: lscr.io/linuxserver/heimdall
    container_name: heimdall
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Bucharest
    volumes:
      - /mnt/prox-share/docker/config/heimdall:/config
    ports:
      - 83:80
      - 443:443
    restart: unless-stopped
```

### Container logs

```bash
thrown
  at /app/www/vendor/facade/ignition/src/SolutionProviders/MergeConflictSolutionProvider.php:52
     48 |     }
     49 |
     50 |     protected function getCurrentBranch(string $directory): string
     51 |     {
  ➜  52 |        $branch = "'".trim(shell_exec("cd ${directory}; git branch | grep \\* | cut -d ' ' -f2"))."'";
     53 | 
     54 |         if ($branch === "''") {
     55 |             $branch = 'current branch';
     56 |         }
PHP Fatal error:  Uncaught Whoops\Exception\ErrorException: Using ${var} in strings is deprecated, use {$var} instead in /app/www/vendor/facade/ignition/src/SolutionProviders/MergeConflictSolutionProvider.php:52
#0 /app/www/vendor/composer/ClassLoader.php(571): Whoops\Run->handleError()
#1 /app/www/vendor/composer/ClassLoader.php(571): include()
#2 /app/www/vendor/composer/ClassLoader.php(428): Composer\Autoload\includeFile()
#3 [internal function]: Composer\Autoload\ClassLoader->loadClass()
#4 /app/www/vendor/facade/ignition/src/SolutionProviders/SolutionProviderRepository.php(50): class_implements()
#5 [internal function]: Facade\Ignition\SolutionProviders\SolutionProviderRepository->Facade\Ignition\SolutionProviders\{closure}()
#6 /app/www/vendor/laravel/framework/src/Illuminate/Collections/Arr.php(717): array_filter()
#7 /app/www/vendor/laravel/framework/src/Illuminate/Collections/Collection.php(358): Illuminate\Support\Arr::where()
#8 /app/www/vendor/facade/ignition/src/SolutionProviders/SolutionProviderRepository.php(49): Illuminate\Support\Collection->filter()
#9 /app/www/vendor/nunomaduro/collision/src/Adapters/Laravel/IgnitionSolutionsRepository.php(36): Facade\Ignition\SolutionProviders\SolutionProviderRepository->getSolutionsForThrowable()
#10 /app/www/vendor/nunomaduro/collision/src/Writer.php(244): NunoMaduro\Collision\Adapters\Laravel\IgnitionSolutionsRepository->getFromThrowable()
#11 /app/www/vendor/nunomaduro/collision/src/Writer.php(123): NunoMaduro\Collision\Writer->renderSolution()
#12 /app/www/vendor/nunomaduro/collision/src/Handler.php(39): NunoMaduro\Collision\Writer->write()
#13 /app/www/vendor/nunomaduro/collision/src/Adapters/Laravel/ExceptionHandler.php(72): NunoMaduro\Collision\Handler->handle()
#14 /app/www/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(185): NunoMaduro\Collision\Adapters\Laravel\ExceptionHandler->renderForConsole()
#15 /app/www/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(171): Illuminate\Foundation\Bootstrap\HandleExceptions->renderForConsole()
#16 /app/www/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(209): Illuminate\Foundation\Bootstrap\HandleExceptions->handleException()
#17 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleShutdown()
#18 {main}
	  thrown in /app/www/vendor/facade/ignition/src/SolutionProviders/MergeConflictSolutionProvider.php on line 52
```

**Comment by j0nnymoe** [comment]
Try using a local folder on your VM rather than a remote mount.

**Comment by vincejv** [comment]
@j0nnymoe 
Same error message on my end, not using a mount
```yml
---
version: "2.1"
services:
  heimdall:
    image: lscr.io/linuxserver/heimdall:latest
    container_name: heimdall
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/Utc
    volumes:
      - ./config:/config
    network_mode: bridge
    ports:
      - 8082:80
    restart: unless-stopped
```

**Comment by vincejv** [comment]
I seem to have figured out the issue, the container needs internet access to pull something from github???

**Comment by j0nnymoe** [comment]
Because it pulls down the app list for any updates.

**Comment by Andy-Voigt** [comment]
I have the same error log spam. But my container have internet access and i can ping google.com without problems.

**Comment by homerr** [comment]
I've just spun the container up with the same docker compose used above, on a Debian netinst system with local storage and have not been able to replicate the issue.

Happy to go into this further, but it seems as if there could be an issue with the system configurations here leading to the issues posted. 

Closing for now.
