### ISSUE TITLE
docker error

### ISSUE THREAD

**Issue by jeongminkim** [linuxserver/docker-heimdall#53]
## Expected Behavior
Starting heimdall ...

ERROR: for heimdall  a bytes-like object is required, not 'str'

ERROR: for heimdall  a bytes-like object is required, not 'str'
Traceback (most recent call last):
  File "site-packages/docker/api/client.py", line 261, in _raise_for_status
  File "site-packages/requests/models.py", line 940, in raise_for_status
requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: http+docker://localhost/v1.22/containers/e21fb74d33f12a0371f850fd335121f6fc0c30c3401366ac67acfa3e45ce6e55/start

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "compose/service.py", line 625, in start_container
  File "compose/container.py", line 241, in start
  File "site-packages/docker/utils/decorators.py", line 19, in wrapped
  File "site-packages/docker/api/container.py", line 1095, in start
  File "site-packages/docker/api/client.py", line 263, in _raise_for_status
  File "site-packages/docker/errors.py", line 31, in create_api_error_from_http_exception
docker.errors.APIError: 500 Server Error: Internal Server Error ("b'driver failed programming external connectivity on endpoint heimdall (ed0af35a5bb7a5cacb79ac4c8e2207c68289c2240cab4b951554f609ebf8c907): Bind for 0.0.0.0:443 failed: port is already allocated'")

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "bin/docker-compose", line 6, in <module>
  File "compose/cli/main.py", line 72, in main
  File "compose/cli/main.py", line 128, in perform_command
  File "compose/cli/main.py", line 1107, in up
  File "compose/cli/main.py", line 1103, in up
  File "compose/project.py", line 570, in up
  File "compose/parallel.py", line 112, in parallel_execute
  File "compose/parallel.py", line 210, in producer
  File "compose/project.py", line 556, in do
  File "compose/service.py", line 568, in execute_convergence_plan
  File "compose/service.py", line 510, in _execute_convergence_start
  File "compose/parallel.py", line 112, in parallel_execute
  File "compose/parallel.py", line 210, in producer
  File "compose/service.py", line 508, in <lambda>
  File "compose/service.py", line 620, in start_container_if_stopped
  File "compose/service.py", line 627, in start_container
TypeError: a bytes-like object is required, not 'str'
[12197] Failed to execute script docker-compose

## Steps to Reproduce
1.
2.
3.
4.

## Environment
**OS:**   Ubuntu 18.04   
**CPU architecture:** x86_64/arm32/arm64      
**How docker service was installed:**      

  heimdall:
    image: linuxserver/heimdall
    container_name: heimdall
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Seoul
    volumes:
      - ./data/heimdall/config:/config
    ports:
      - 80:80
      - 443:443
    restart: unless-stopped

**Comment by aptalca** [comment]
`Bind for 0.0.0.0:443 failed: port is already allocated'")`
Map a different port

**Comment by jeongminkim** [comment]
> `Bind for 0.0.0.0:443 failed: port is already allocated'")`
> Map a different port

Thank you!!! my mistake..
